name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/neumannalex/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore ./Tree/Tree.csproj
    - name: Build Debug
      run: dotnet build --no-restore ./Tree/Tree.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Tree/Tree.csproj
    - name: Build Release
      run: dotnet build --configuration Release --no-restore ./Tree/Tree.csproj
    - name: Create the package
      run: dotnet pack --configuration Release ./Tree/Tree.csproj
    - name: Publish the package to Github Packages
      run: dotnet nuget push ./Tree/bin/Release/*.nupkg
